### PR TITLE
Allow defining a 'static_folder' on the flask-themes blueprint

### PR DESCRIPTION
**Pull request by Jaza**
Allow defining a 'static_folder' on the flask-themes blueprint, for compatibility with flask-assets

### CODE REVIEW

**Comment by sysr-q** [comment]
Thanks, merged.

**Comment by Jaza** [comment]
Thanks for the merge, and for releasing 0.1.4 with the changes, sysr-q.

Could you add a source release to pypi, please? The current binary release won't download for me (with "pip install Flask-Themes2==0.1.4"), I guess because I'm not running the specified "Linux-3.19.2-1-ARCH-x86_64-with-glibc2.3.4" (I'm on Ubuntu 14.04, with Linux kernel 3.13.0-48, and glibc 2.19-0).

**Comment by sysr-q** [comment]
My bad, totally forgot about sdist. Haven't used PyPI in ages. 
Uploaded a source release just now.

**Comment by Jaza** [comment]
Thanks! Working now.

**Pull request merged**
